// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpgfjgtqtslvaryhnaqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ2ZqZ3RxdHNsdmFyeWhuYXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODI3MDQsImV4cCI6MjA2NzY1ODcwNH0.8OHbjEWE08KvQDEF4KXUW1ohDJHWM4PIn0M1w_TSSho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});